import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { FiAlertTriangle, FiCheckCircle, FiShield, FiXCircle } from 'react-icons/fi';
import { verifyDocument } from '../utils/documentVerificationApi';
import { formatDateTime } from '../utils/formatDate';

const STATUS_META = {
  valid: {
    icon: FiCheckCircle,
    title: 'Document verified',
    tone: 'border-emerald-200 bg-emerald-50 text-emerald-900 dark:border-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-100',
    badge: 'bg-emerald-600 text-white',
  },
  altered: {
    icon: FiAlertTriangle,
    title: 'Document altered',
    tone: 'border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100',
    badge: 'bg-amber-600 text-white',
  },
  missing: {
    icon: FiAlertTriangle,
    title: 'Source record missing',
    tone: 'border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100',
    badge: 'bg-amber-600 text-white',
  },
  not_found: {
    icon: FiXCircle,
    title: 'Not recognized',
    tone: 'border-red-200 bg-red-50 text-red-900 dark:border-red-800 dark:bg-red-950/30 dark:text-red-100',
    badge: 'bg-red-600 text-white',
  },
};

const DocumentVerify = () => {
  const { code } = useParams();
  const [loading, setLoading] = useState(true);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;

    (async () => {
      setLoading(true);
      setError('');
      setResult(null);

      if (!code) {
        if (!cancelled) {
          setError('Verification code is missing from the URL.');
          setLoading(false);
        }
        return;
      }

      try {
        const payload = await verifyDocument(code);
        if (!cancelled) setResult(payload);
      } catch (err) {
        if (!cancelled) setError(err.message || 'Verification failed.');
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code]);

  const statusKey = result?.authentic ? result?.status || 'not_found' : 'not_found';
  const meta = STATUS_META[statusKey] || STATUS_META.not_found;
  const Icon = meta.icon;

  return (
    <div className="min-h-screen bg-stone-100 px-4 py-10 dark:bg-stone-950">
      <div className="mx-auto max-w-2xl rounded-2xl border border-stone-200 bg-white p-8 shadow-sm dark:border-stone-800 dark:bg-stone-900">
        <div className="mb-6 flex items-center gap-3">
          <div className="rounded-xl bg-emerald-100 p-3 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">
            <FiShield className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-2xl font-semibold text-stone-900 dark:text-stone-100">Document Verification</h1>
            <p className="text-sm text-stone-500">Confirm whether this PDF was generated by Sitometrics.</p>
          </div>
        </div>

        {code ? (
          <p className="mb-4 break-all font-mono text-xs text-stone-500">Code: {code}</p>
        ) : null}

        {loading ? (
          <p className="text-sm text-stone-500">Checking verification code…</p>
        ) : error ? (
          <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-800 dark:bg-red-950/30 dark:text-red-200">
            {error}
          </div>
        ) : result ? (
          <div className={`rounded-xl border p-5 ${meta.tone}`}>
            <div className="mb-4 flex items-start gap-3">
              <Icon className="mt-0.5 h-6 w-6 shrink-0" />
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <h2 className="text-lg font-semibold">{meta.title}</h2>
                  <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold uppercase tracking-wide ${meta.badge}`}>
                    {result.authentic ? result.status : 'not found'}
                  </span>
                </div>
                <p className="mt-2 text-sm">{result.message || 'No verification message was returned.'}</p>
              </div>
            </div>

            {result.authentic ? (
              <dl className="grid gap-3 text-sm sm:grid-cols-2">
                <div>
                  <dt className="font-medium text-stone-500">Document type</dt>
                  <dd>{result.document_type_label || result.document_type || '—'}</dd>
                </div>
                <div>
                  <dt className="font-medium text-stone-500">Reference</dt>
                  <dd>{result.document_reference || '—'}</dd>
                </div>
                <div>
                  <dt className="font-medium text-stone-500">Verification code</dt>
                  <dd className="break-all font-mono text-xs">{result.verification_code || code}</dd>
                </div>
                <div>
                  <dt className="font-medium text-stone-500">Generated at</dt>
                  <dd>{formatDateTime(result.generated_at)}</dd>
                </div>
              </dl>
            ) : null}
          </div>
        ) : (
          <div className="rounded-xl border border-stone-200 bg-stone-50 p-4 text-sm text-stone-600 dark:border-stone-700 dark:bg-stone-950/40 dark:text-stone-300">
            No verification result was returned.
          </div>
        )}
      </div>
    </div>
  );
};

export default DocumentVerify;
